export let UserPreferences = {
    hobby_Reading: false,
    hobby_Writing: false,
    hobby_Art: false,
    hobby_Music: false,
    hobby_Sports: false,
    hobby_Gaming: false,
    hobby_Cooking: false,
    hobby_Photography: false,
    hobby_Hiking: false,
    hobby_Cycling: false,
    hobby_Yoga: false,
    hobby_Dancing: false,
    hobby_Crafting: false,
    hobby_Gardening: false,
    hobby_Fishing: false,
    hobby_Gym: false,
    interest_Travelling: false,
    interest_History: false,
    interest_Movies: false,
    interest_Theater: false,
    interest_Science: false,
    interest_Pets: false,
    interest_Volunteering: false,
    interest_Nature: false,
    interest_Fitness: false,
    dietary_Vegan: false,
    dietary_Vegetarian: false,
    dietary_GlutenFree: false,
    food_Markets: false,
    food_Asian: false,
    food_Italian: false,
    food_Indian: false,
    food_Mexican: false,
    food_Seafood: false,
    food_Barbecue: false,
    food_Mediterranean: false,
    food_FastFood: false,
    food_Desserts: false,
    location_Bar: false,
    location_Cafe: false,
    location_Restaurant: false
};

export type UserPreferences = typeof UserPreferences;
